# see https://github.com/kubernetes/examples/blob/master/staging/volumes/flexvolume/deploy/deploy.sh
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deploy-flexvolume-drivers
spec:
  selector:
    matchLabels:
      app: deploy-flexvolume-drivers
  template:
    metadata:
      labels:
        app: deploy-flexvolume-drivers
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: install
        image: busybox
        command:
          - "sh"
          - "-exc"
          - |
            VENDOR=ramax.com
            DRIVERS="$(cd /flexvolume-drivers; echo *)"

            for driver in $DRIVERS; do
                driver_dir=$VENDOR${VENDOR:+"~"}${driver}
                mkdir -p "/flexmnt/$driver_dir"
                tmp_driver=.tmp_$driver
                cp "/flexvolume-drivers/$driver" "/flexmnt/$driver_dir/$tmp_driver"
                chown root:root "/flexmnt/$driver_dir/$tmp_driver"
                chmod 755 "/flexmnt/$driver_dir/$tmp_driver"
                mv -f "/flexmnt/$driver_dir/$tmp_driver" "/flexmnt/$driver_dir/$driver"
            done

            sleep infinity


        securityContext:
#          privileged: true
        volumeMounts:
          - mountPath: /flexmnt
            name: flexvolume-mount
          - mountPath: /flexvolume-drivers
            name: flexvolume-drivers

      volumes:
      - name: flexvolume-mount
        hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
      - name: flexvolume-drivers
        configMap:
          name: flexvolume-drivers

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-flexvolume-drivers

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-flexvolume-drivers
subjects:
- kind: ServiceAccount
  name: deploy-flexvolume-drivers
roleRef:
  kind: ClusterRole
  name: privileged
  apiGroup: rbac.authorization.k8s.io
